"""Project the Love Hurts registry records into products.js for the prototypes.

Product facts come only from get_product(). Images are limited to the ones
eyes-on checked against their references on 2026-09-27; anything excluded is
listed with the reason, and the build fails if an allowed file is missing.

    .venv/bin/python _prototype/love-hurts/build_data.py
"""

from __future__ import annotations

import json
import os
from pathlib import Path

from PIL import Image

from skyyrose.core.product import get_product

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
THEME = REPO / "wordpress-theme" / "skyyrose-flagship"

SKUS = ("lh-002", "lh-006", "lh-003", "lh-004", "lh-005")

# Roles that passed the side-by-side check. Everything else is withheld.
APPROVED_ROLES = {
    "lh-002": ("front",),
    "lh-006": ("front", "back"),
    "lh-003": ("front", "back", "back_packshot"),
    "lh-004": ("front", "back"),
    "lh-005": ("front", "back_packshot"),
}

WITHHELD = {
    "lh-002.back": "no verified black back shot yet (registry gap; the white-joggers binding was removed, bug-361)",
    "lh-005.back": "the-fannie-back-model.webp is a processed copy of the real back photo; the real photo is shown instead",
    "lh-002.packshot": "400x360, too small for editorial use",
}

# Box around the item for sale in each front image, as fractions of the frame
# (x, y, w, h). Checked by cropping on 2026-09-27; styling pieces fall outside it.
FOCUS = {
    "lh-002": (0.30, 0.46, 0.38, 0.50),
    "lh-006": (0.43, 0.45, 0.31, 0.49),
    "lh-003": (0.35, 0.44, 0.30, 0.24),
    "lh-004": (0.20, 0.24, 0.44, 0.34),
    "lh-005": (0.33, 0.21, 0.30, 0.25),
}

# Founder drawings checked alongside the renders (assets/products/references/).
REFERENCES = {
    "lh-002": "assets/products/references/lh-002-techflat-front.jpeg",
    "lh-006": "assets/products/references/lh-006-techflat-front.jpeg",
    "lh-003": "assets/products/references/lh-003-techflat-front.jpeg",
    "lh-004": "assets/products/references/lh-004-techflat-back.jpeg",
}


def _rel(theme_path: str, root: Path = THEME) -> str:
    path = root / theme_path
    if not path.is_file():
        raise FileNotFoundError(f"approved image missing: {path}")
    return os.path.relpath(path, HERE)


def _record(sku: str) -> dict:
    p = get_product(sku)
    cat, garment = p["catalog"], p["garment"]
    images = {}
    for role in APPROVED_ROLES[sku]:
        entry = p["images"].get(role)
        path = entry.get("path") if isinstance(entry, dict) else entry
        if not path:
            raise KeyError(f"{sku} has no {role} image in the registry")
        images[role] = _rel(path)
    with Image.open(HERE / images["front"]) as front:
        width, height = front.size
    x, y, w, h = FOCUS[sku]
    return {
        "sku": sku,
        "name": p["name"],
        "price": int(cat["price"]),
        "color": (
            garment["color"]["value"] if isinstance(garment["color"], dict) else garment["color"]
        ),
        "sizes": (
            garment["available_sizes"]["value"]
            if isinstance(garment["available_sizes"], dict)
            else garment["available_sizes"]
        ),
        "description": cat["description"],
        "branding": cat["branding_spec"],
        "preorder": str(cat["is_preorder"]) == "1",
        "edition": int(cat["edition_size"]) if cat["edition_size"] else None,
        "images": images,
        "focus": {"x": x, "y": y, "w": w, "h": h, "width": width, "height": height},
        "reference": _rel(REFERENCES[sku], REPO) if sku in REFERENCES else None,
    }


def main() -> None:
    data = {"products": [_record(s) for s in SKUS], "withheld": WITHHELD}
    out = HERE / "products.js"
    out.write_text(
        "// Generated by build_data.py from get_product(). Do not edit.\n"
        f"window.LH = {json.dumps(data, indent=2, ensure_ascii=False)};\n",
        encoding="utf-8",
    )
    print(f"wrote {out.relative_to(REPO)}: {len(data['products'])} products")


if __name__ == "__main__":
    main()
