"""Project the Love Hurts registry records into products.js for the prototypes.

Product facts come only from get_product(). Images are limited to the ones
eyes-on checked against their references on 2026-09-27; anything excluded is
listed with the reason, and the build fails if an allowed file is missing.

    .venv/bin/python _prototype/love-hurts/build_data.py
"""

from __future__ import annotations

import json
import os
from pathlib import Path

from skyyrose.core.product import get_product

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
THEME = REPO / "wordpress-theme" / "skyyrose-flagship"

SKUS = ("lh-002", "lh-006", "lh-003", "lh-004", "lh-005")

# Roles that passed the side-by-side check. Everything else is withheld.
APPROVED_ROLES = {
    "lh-002": ("front",),
    "lh-006": ("front", "back"),
    "lh-003": ("front", "back", "back_packshot"),
    "lh-004": ("front", "back"),
    "lh-005": ("front",),
}

WITHHELD = {
    "lh-002.back": "love-hurts-joggers-back-model.webp shows WHITE joggers; lh-002 is black",
    "lh-002.back_packshot": "same wrong-garment file as lh-002.back",
    "lh-005.back": "the-fannie-back-model.webp carries a blue-navy cast (no-blue rule)",
    "lh-002.packshot": "400x360, too small for editorial use",
}

# Founder drawings checked alongside the renders (assets/products/references/).
REFERENCES = {
    "lh-002": "assets/products/references/lh-002-techflat-front.jpeg",
    "lh-006": "assets/products/references/lh-006-techflat-front.jpeg",
    "lh-003": "assets/products/references/lh-003-techflat-front.jpeg",
    "lh-004": "assets/products/references/lh-004-techflat-back.jpeg",
}


def _rel(theme_path: str, root: Path = THEME) -> str:
    path = root / theme_path
    if not path.is_file():
        raise FileNotFoundError(f"approved image missing: {path}")
    return os.path.relpath(path, HERE)


def _record(sku: str) -> dict:
    p = get_product(sku)
    cat, garment = p["catalog"], p["garment"]
    images = {}
    for role in APPROVED_ROLES[sku]:
        entry = p["images"].get(role)
        path = entry.get("path") if isinstance(entry, dict) else entry
        if not path:
            raise KeyError(f"{sku} has no {role} image in the registry")
        images[role] = _rel(path)
    return {
        "sku": sku,
        "name": p["name"],
        "price": int(cat["price"]),
        "color": (
            garment["color"]["value"] if isinstance(garment["color"], dict) else garment["color"]
        ),
        "sizes": (
            garment["available_sizes"]["value"]
            if isinstance(garment["available_sizes"], dict)
            else garment["available_sizes"]
        ),
        "description": cat["description"],
        "branding": cat["branding_spec"],
        "preorder": str(cat["is_preorder"]) == "1",
        "edition": int(cat["edition_size"]) if cat["edition_size"] else None,
        "images": images,
        "reference": _rel(REFERENCES[sku], REPO) if sku in REFERENCES else None,
    }


def main() -> None:
    data = {"products": [_record(s) for s in SKUS], "withheld": WITHHELD}
    out = HERE / "products.js"
    out.write_text(
        "// Generated by build_data.py from get_product(). Do not edit.\n"
        f"window.LH = {json.dumps(data, indent=2, ensure_ascii=False)};\n",
        encoding="utf-8",
    )
    print(f"wrote {out.relative_to(REPO)}: {len(data['products'])} products")


if __name__ == "__main__":
    main()
