// Generated by build_data.py from get_product(). Do not edit.
window.LH = {
  "products": [
    {
      "sku": "lh-002",
      "name": "Love Hurts Joggers (Black)",
      "price": 95,
      "color": "Black",
      "sizes": [
        "S",
        "M",
        "L",
        "XL",
        "2XL",
        "3XL"
      ],
      "description": "Oakland grit meets luxury. Solid black body with white contrast side-panels running vertically from waist to ankle. White flat drawstring. The Love Hurts heart-rose-composite embroidered on the left thigh — the heart-and-thorns lockup with roses emerging from the top, rendered in red, green, and crimson on the black fabric. Mid-weight cotton-fleece, athletic-fit through the leg, ribbed ankle cuffs. Mirror white colorway available as lh-006.",
      "branding": "Heart-rose-composite (Love Hurts heart-and-thorns lockup) embroidered on the left thigh. White contrast side-panel running vertically on both side seams. White drawstring.",
      "preorder": false,
      "edition": 250,
      "images": {
        "front": "../../wordpress-theme/skyyrose-flagship/assets/images/products/lh-002-onmodel.webp"
      },
      "reference": "../../assets/products/references/lh-002-techflat-front.jpeg"
    },
    {
      "sku": "lh-006",
      "name": "Love Hurts Joggers (White)",
      "price": 95,
      "color": "White",
      "sizes": [
        "S",
        "M",
        "L",
        "XL",
        "2XL",
        "3XL"
      ],
      "description": "The mirror of lh-002 in white. Solid white body with black contrast side-panels running vertically from waist to ankle. White flat drawstring. The Love Hurts heart-rose-composite embroidered on the left thigh — the heart-and-thorns lockup with roses emerging from the top, rendered in red, green, and crimson on the white fabric. Mid-weight cotton-fleece, athletic-fit through the leg, ribbed ankle cuffs. Mirror black colorway available as lh-002.",
      "branding": "Heart-rose-composite (Love Hurts heart-and-thorns lockup) embroidered on the left thigh. Black contrast side-panel running vertically on both side seams. White drawstring.",
      "preorder": false,
      "edition": 250,
      "images": {
        "front": "../../wordpress-theme/skyyrose-flagship/assets/images/products/lh-006-onmodel.webp",
        "back": "../../wordpress-theme/skyyrose-flagship/assets/images/products/love-hurts-joggers-white-back-model.webp"
      },
      "reference": "../../assets/products/references/lh-006-techflat-front.jpeg"
    },
    {
      "sku": "lh-003",
      "name": "Love Hurts Basketball Shorts",
      "price": 75,
      "color": "White",
      "sizes": [
        "S",
        "M",
        "L",
        "XL",
        "2XL",
        "3XL"
      ],
      "description": "Oakland-inspired luxury streetwear. Defiant rose design on breathable mesh.",
      "branding": "Sublimated rose logo throughout the shorts. Big sublimated 'Love Hurts' logo on the left side. Additional 'Love Hurts' and rose logos stitched on the mesh sides of the shorts.",
      "preorder": false,
      "edition": 250,
      "images": {
        "front": "../../wordpress-theme/skyyrose-flagship/assets/images/products/hub/lh-003-front.webp",
        "back": "../../wordpress-theme/skyyrose-flagship/assets/images/products/love-hurts-basketball-shorts-back-model.webp",
        "back_packshot": "../../wordpress-theme/skyyrose-flagship/assets/images/products/lh-003-real-back.jpg"
      },
      "reference": "../../assets/products/references/lh-003-techflat-front.jpeg"
    },
    {
      "sku": "lh-004",
      "name": "Love Hurts Bomber Jacket",
      "price": 265,
      "color": "White/Black",
      "sizes": [
        "S",
        "M",
        "L",
        "XL",
        "2XL",
        "3XL"
      ],
      "description": "Oakland street couture. Satin bomber with bold fire-red script and a hidden rose garden in the hood.",
      "branding": "'Love Hurts' logo lettering across the front. Inside of the hood features a sublimated rose logo. BACK: large 'Heart and Rose' Love Hurts logo centered.",
      "preorder": false,
      "edition": 250,
      "images": {
        "front": "../../wordpress-theme/skyyrose-flagship/assets/images/products/lh-004-onmodel.webp",
        "back": "../../wordpress-theme/skyyrose-flagship/assets/images/products/lh-004-bomber-back.webp"
      },
      "reference": "../../assets/products/references/lh-004-techflat-back.jpeg"
    },
    {
      "sku": "lh-005",
      "name": "The Fannie",
      "price": 45,
      "color": "Black",
      "sizes": [
        "One Size"
      ],
      "description": "Oakland luxury meets everyday utility. The essential Love Hurts fanny pack with premium embroidery.",
      "branding": "High-end leather fanny pack construction. The heart-and-rose logo positioned where the dot of the 'I' in 'FANNIE' would go.",
      "preorder": true,
      "edition": 250,
      "images": {
        "front": "../../wordpress-theme/skyyrose-flagship/assets/images/products/lh-005-onmodel.webp"
      },
      "reference": null
    }
  ],
  "withheld": {
    "lh-002.back": "love-hurts-joggers-back-model.webp shows WHITE joggers; lh-002 is black",
    "lh-002.back_packshot": "same wrong-garment file as lh-002.back",
    "lh-005.back": "the-fannie-back-model.webp carries a blue-navy cast (no-blue rule)",
    "lh-002.packshot": "400x360, too small for editorial use"
  }
};
