#!/usr/bin/env bash
# Vendor three.js modules into assets/js/lib/three/ for the PDP 3D viewer.
#
# Flattens build/three.module.min.js + the examples/jsm addons the viewer needs
# into ONE directory and rewrites their import specifiers so they load with no
# bundler under the theme CSP (script-src 'self'). Addons stay byte-identical to
# upstream apart from the import lines: KTX2Loader builds its worker from
# Function.prototype.toString(), which name-mangling would break, so nothing is
# re-minified here. Writes VENDOR.md with a sha256 per file.
#
# Usage: bash scripts/vendor-three.sh [version]    (default 0.170.0 = mascot's r170)
set -euo pipefail

VERSION="${1:-0.170.0}"
THEME_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DST="$THEME_DIR/assets/js/lib/three-${VERSION}"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

(cd "$WORK" && npm pack "three@${VERSION}" --silent > /dev/null && tar -xzf "three-${VERSION}.tgz")
SRC="$WORK/package"

rm -rf "$DST"
mkdir -p "$DST/basis"

cp "$SRC/build/three.module.min.js" "$DST/three.module.min.js"
cp "$SRC/LICENSE" "$DST/LICENSE"
cp "$SRC/examples/jsm/libs/basis/basis_transcoder.js" "$DST/basis/basis_transcoder.js"
cp "$SRC/examples/jsm/libs/basis/basis_transcoder.wasm" "$DST/basis/basis_transcoder.wasm"
cp "$SRC/examples/jsm/libs/meshopt_decoder.module.js" "$DST/meshopt_decoder.module.js"
cp "$SRC/examples/jsm/libs/zstddec.module.js" "$DST/zstddec.module.js"
cp "$SRC/examples/jsm/libs/ktx-parse.module.js" "$DST/ktx-parse.module.js"
cp "$SRC/examples/jsm/utils/WorkerPool.js" "$DST/WorkerPool.js"

rewrite() {
  # $1 = upstream path under package/, $2 = flat destination filename
  sed \
    -e "s#from 'three'#from './three.module.min.js'#" \
    -e "s#from '\.\./utils/#from './#" \
    -e "s#from '\.\./libs/#from './#" \
    -e "s#from '\.\./math/#from './#" \
    "$SRC/$1" > "$DST/$2"
}
rewrite examples/jsm/loaders/GLTFLoader.js GLTFLoader.js
rewrite examples/jsm/loaders/KTX2Loader.js KTX2Loader.js
rewrite examples/jsm/controls/OrbitControls.js OrbitControls.js
rewrite examples/jsm/environments/RoomEnvironment.js RoomEnvironment.js
rewrite examples/jsm/utils/BufferGeometryUtils.js BufferGeometryUtils.js
rewrite examples/jsm/math/ColorSpaces.js ColorSpaces.js

# Any specifier still pointing outside the flat directory is a vendoring bug.
if grep -nE "from '(three|\.\./)" "$DST"/*.js; then
  echo "unrewritten import specifier(s) above" >&2
  exit 1
fi

{
  echo "# three.js r$(echo "$VERSION" | cut -d. -f2) (npm three@${VERSION}) — vendored for the PDP 3D viewer"
  echo
  echo "Generated by \`scripts/vendor-three.sh ${VERSION}\` (same revision as the mascot's"
  echo "jsdelivr import). Flattened from build/ + examples/jsm/; the ONLY edits are import"
  echo "specifiers (\`'three'\` -> \`'./three.module.min.js'\`, \`'../utils|libs|math/x'\` -> \`'./x'\`)."
  echo "Nothing is re-minified: KTX2Loader assembles its worker from"
  echo "Function.prototype.toString(), which name-mangling breaks."
  echo
  echo "| file | sha256 | bytes |"
  echo "| --- | --- | --- |"
  (cd "$DST" && find . -type f ! -name VENDOR.md | sort | while read -r f; do
    printf '| %s | %s | %s |\n' "${f#./}" "$(shasum -a 256 "$f" | cut -c1-64)" "$(wc -c < "$f")"
  done)
} > "$DST/VENDOR.md"

du -sk "$DST" | awk '{print "vendored total KB:", $1}'
