"""Precision cleanup: tidy only what an edit touched or orphaned, never the rest of the file.

The old PostToolUse hook ran isort -> ruff --fix -> black over the WHOLE file after every edit,
which rewrote legacy lines the edit never touched and, on 2026-06-22, deleted an ``import os``
that had been added one edit before its first use (tasks/lessons.md). These tests pin the
contract that replaces it.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from scripts import precision_cleanup as pc

pytestmark = pytest.mark.skipif(
    not (shutil.which("black") and shutil.which("ruff") and shutil.which("isort")),
    reason="needs black, ruff and isort on PATH",
)

PYPROJECT = """\
[tool.black]
line-length = 100
target-version = ["py313"]
exclude = '''
/(
    \\.claude
)/
'''

[tool.ruff]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100
"""


@pytest.fixture
def root(tmp_path: Path) -> Path:
    (tmp_path / "pyproject.toml").write_text(PYPROJECT)
    return tmp_path


def run(root: Path, baseline: str | None, current: str, rel: str = "mod.py") -> str:
    out, _notes = pc.cleanup_text(rel, baseline, current, root)
    return out


LEGACY = "def legacy( a,b ):\n    x=1\n    return a+b\n"


def test_black_touches_only_the_changed_lines(root):
    current = LEGACY + "\n\ndef new_fn( a,b ):\n    return a+b\n"
    out = run(root, LEGACY, current)
    assert out.startswith(LEGACY), "legacy lines must stay byte-identical"
    assert "def new_fn(a, b):" in out


def test_a_brand_new_file_is_formatted_whole(root):
    out = run(root, "", LEGACY)
    assert "def legacy(a, b):" in out and "x = 1" in out


def test_no_baseline_for_an_existing_file_is_a_no_op(root):
    assert run(root, None, LEGACY) == LEGACY


def test_an_import_orphaned_by_the_edit_is_removed(root):
    baseline = "import os\nimport sys\n\n\ndef f():\n    return os.getcwd(), sys.argv\n"
    current = "import os\nimport sys\n\n\ndef f():\n    return sys.argv\n"
    out = run(root, baseline, current)
    assert "import os" not in out
    assert "import sys" in out


def test_an_import_added_before_its_first_use_survives(root):
    """The 2026-06-22 failure: a new import must not be deleted between two edits."""
    baseline = "import sys\n\n\ndef f():\n    return sys.argv\n"
    current = "import json\nimport sys\n\n\ndef f():\n    return sys.argv\n"
    assert "import json" in run(root, baseline, current)


def test_legacy_unused_imports_are_left_alone(root):
    baseline = "import os\n\n\ndef f():\n    return 1\n"
    current = "import os\n\n\ndef f():\n    return 2\n"
    assert run(root, baseline, current) == current


def test_isort_runs_only_when_the_edit_touched_imports_on_a_clean_baseline(root):
    clean = "import os\nimport sys\n\nprint(os, sys)\n"
    edited = "import sys\nimport os\nimport json\n\nprint(os, sys, json)\n"
    assert run(root, clean, edited).splitlines()[:3] == ["import json", "import os", "import sys"]

    unsorted_baseline = "import sys\nimport os\n\nprint(os, sys)\n"
    edited_elsewhere = "import sys\nimport os\n\nprint(os, sys, 1)\n"
    assert run(root, unsorted_baseline, edited_elsewhere) == edited_elsewhere


@pytest.mark.parametrize(
    "rel",
    [".claude/hooks/x.py", "node_modules/p/x.py", ".venv/lib/x.py", "wordpress-theme/vendor/x.py"],
)
def test_excluded_and_vendored_paths_are_skipped(root, rel):
    ugly = "x=1\n"
    assert run(root, "", ugly, rel) == ugly


def test_generated_files_are_skipped(root):
    generated = "# @generated by tool\nx=1\n"
    assert run(root, "", generated) == generated


def test_a_syntax_error_leaves_the_file_untouched(root):
    broken = "def f(:\n    x=1\n"
    assert run(root, "", broken) == broken


def test_a_missing_formatter_is_a_no_op_not_a_crash(root, monkeypatch):
    monkeypatch.setattr(pc, "_tool", lambda name, root: None)
    assert run(root, "", LEGACY) == LEGACY


def test_cleanup_is_idempotent(root):
    current = LEGACY + "\n\ndef new_fn( a,b ):\n    return a+b\n"
    once = run(root, LEGACY, current)
    assert run(root, LEGACY, once) == once


def _hook(root: Path, payload: dict | str) -> subprocess.CompletedProcess:
    stdin = payload if isinstance(payload, str) else json.dumps(payload)
    return subprocess.run(
        [sys.executable, "-m", "scripts.precision_cleanup"],
        input=stdin,
        capture_output=True,
        text=True,
        cwd=Path(__file__).resolve().parents[1],
        env={"PATH": __import__("os").environ["PATH"], "PRECISION_CLEANUP_ROOT": str(root)},
    )


def test_hook_entry_formats_an_edit_in_place_and_exits_zero(root):
    target = root / "mod.py"
    original = LEGACY
    edited = LEGACY + "\n\ndef new_fn( a,b ):\n    return a+b\n"
    target.write_text(edited)
    payload = {
        "tool_name": "Edit",
        "tool_input": {"file_path": str(target)},
        "tool_response": {"filePath": str(target), "originalFile": original},
    }
    proc = _hook(root, payload)
    assert proc.returncode == 0, proc.stderr
    after = target.read_text()
    assert after.startswith(LEGACY) and "def new_fn(a, b):" in after


def test_hook_entry_never_fails_on_garbage_or_missing_files(root):
    assert _hook(root, "not json").returncode == 0
    gone = {"tool_name": "Edit", "tool_input": {"file_path": str(root / "nope.py")}}
    assert _hook(root, gone).returncode == 0
    non_py = {"tool_name": "Edit", "tool_input": {"file_path": str(root / "x.txt")}}
    assert _hook(root, non_py).returncode == 0


REPO = Path(__file__).resolve().parents[1]


def _post_tool_use_commands() -> list[str]:
    settings = json.loads((REPO / ".claude" / "settings.json").read_text())
    return [
        hook["command"]
        for entry in settings["hooks"]["PostToolUse"]
        if "Edit" in entry.get("matcher", "")
        for hook in entry["hooks"]
    ]


def test_exactly_one_python_formatter_is_registered_on_edit():
    """Hooks on one event run concurrently: a whole-file formatter beside this one would race
    it and clobber the range-limited result, silently ending the precision guarantee."""
    commands = _post_tool_use_commands()
    assert sum("precision-cleanup.sh" in c for c in commands) == 1
    for whole_file in ("python-format-on-write.sh", "black ", "ruff format", "isort "):
        assert not [c for c in commands if whole_file in c], f"{whole_file!r} would race it"
    assert not (REPO / ".claude/hooks/python-format-on-write.sh").exists()


def test_the_wrapper_is_executable_and_never_fails():
    wrapper = REPO / ".claude" / "hooks" / "precision-cleanup.sh"
    assert wrapper.stat().st_mode & 0o111, "wrapper must be executable"
    proc = subprocess.run(["bash", str(wrapper)], input="garbage", capture_output=True, text=True)
    assert proc.returncode == 0
