const pw=require('/Users/theceo/DevSkyy/node_modules/playwright');
const fs=require('fs'),assert=require('assert');const path=require('path');
const base='https://staging-7e48-skyyrose.wpcomstaging.com',out=path.resolve(__dirname,'../evidence');
(async()=>{const results=[];for(const engine of ['chromium','webkit']){const b=await pw[engine].launch();try{for(const width of [engine==='chromium'?390:1440]){const context=await b.newContext({viewport:{width,height:900}});const p=await context.newPage();p.setDefaultTimeout(30000);const errors=[];p.on('pageerror',e=>errors.push(e.message));const r={engine,width,errors,checks:[]};try{
await p.goto(base+'/',{waitUntil:'load'});await p.locator('[data-sr2-menu]').click();await p.waitForFunction(()=>document.querySelector('[data-sr2-menu]').getAttribute('aria-expanded')==='true');await p.keyboard.press('Escape');await p.waitForFunction(()=>document.querySelector('[data-sr2-menu]').getAttribute('aria-expanded')==='false');console.log(engine,width,'progress');r.checks.push('menu keyboard dismissal');
await p.goto(base+'/product/br-003/',{waitUntil:'load'});await p.locator('form.cart select[name="attribute_size"]').selectOption('M');await p.waitForFunction(()=>Number(document.querySelector('input[name=variation_id]')?.value)>0&&!document.querySelector('button.single_add_to_cart_button').classList.contains('disabled'));await p.locator('button.single_add_to_cart_button').click();await p.waitForFunction(()=>Number(document.querySelector('.sr2-header__bag-count')?.textContent)>0);await p.goto(base+'/cart/',{waitUntil:'load'});r.cart100=await p.locator('main').innerText();assert(r.cart100.includes('$100.00'));assert(r.cart100.includes('$17.00'));assert(!r.cart100.includes('Free standard shipping'));console.log(engine,width,'progress');r.checks.push('below-threshold standard shipping');
await p.locator('input.qty').fill('2');await p.locator('input.qty').dispatchEvent('change');await p.getByRole('button',{name:'Update bag',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.cart-subtotal')?.innerText.includes('$200.00'));await p.waitForFunction(()=>document.querySelector('main')?.innerText.includes('Free standard shipping'));r.cart200=await p.locator('main').innerText();assert(r.cart200.includes('$200.00'));console.log(engine,width,'progress');r.checks.push('free shipping at exact $200 threshold');
await p.goto(base+'/checkout/',{waitUntil:'load'});const shipDifferent=p.locator('#ship-to-different-address-checkbox');if(await shipDifferent.isChecked())await shipDifferent.uncheck();await p.locator('#billing_address_1').fill('1 Test Street');await p.locator('#billing_country').selectOption('US');await p.locator('#billing_state').selectOption('CA');await p.locator('#billing_postcode').fill('94612');await p.locator('#billing_city').fill('Oakland');await p.locator('#billing_postcode').dispatchEvent('change');await p.waitForFunction(()=>document.querySelector('.woocommerce-shipping-totals')?.innerText.includes('Free standard shipping'));await p.waitForTimeout(1500);r.us=await p.locator('#order_review').innerText();assert(r.us.includes('Free standard shipping'));console.log(engine,width,'progress');r.checks.push('US checkout shipping');
await p.locator('#billing_country').selectOption('CA');await p.locator('#billing_state').selectOption('ON');await p.locator('#billing_postcode').fill('M5V 2T6');await p.locator('#billing_city').fill('Toronto');await p.locator('#billing_postcode').dispatchEvent('change');await p.waitForFunction(()=>{const t=document.querySelector('.woocommerce-shipping-totals')?.innerText||'';return /no shipping|no shipment|not available|cannot be shipped|not been entered/i.test(t)});await p.waitForTimeout(1000);r.canada=await p.locator('#order_review').innerText();console.log(engine,width,'progress');r.checks.push('unsupported international destination fails closed');
r.paymentDisabled=await p.locator('#payment').innerText();assert(r.paymentDisabled.includes('no available payment methods'));console.log(engine,width,'progress');r.checks.push('payment-disabled state truthful');await p.screenshot({path:path.join(out,`acceptance-${engine}-${width}-checkout.png`),fullPage:true});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(errors.length,0);r.pass=true;
}catch(e){r.failure=e.message;r.lastMain=await p.locator('main').innerText().catch(()=>null);process.exitCode=1}finally{try{await p.goto(base+'/cart/',{waitUntil:'domcontentloaded'});const remove=p.locator('a.sr2-cart__remove');if(await remove.count())await remove.click();await p.waitForFunction(()=>document.querySelector('main')?.innerText.includes('Your cart is currently empty.'));r.cartCleaned=true}catch(e){r.cleanupError=e.message}results.push(r);fs.writeFileSync(path.join(out,'acceptance.json'),JSON.stringify(results,null,2));console.log(JSON.stringify({engine,width,pass:r.pass,checks:r.checks,failure:r.failure,cartCleaned:r.cartCleaned}));await context.close()}}
}finally{await b.close()}}})().catch(e=>{console.error(e);process.exitCode=1});
