"""Build/check standalone V2 analytics projections from tested V1 protocol sources.

Only build-time references cross theme directories. Packaged V2 is self-contained.
V2-specific bootstrapping/card rendering lives outside these projections.
"""

import argparse
import re
import subprocess
from pathlib import Path

THEME = Path(__file__).resolve().parents[1]
SOURCE = THEME.parent / "skyyrose-flagship"
PENDING: dict[str, str] = {}


def function(file: str, name: str) -> str:
    text = (SOURCE / file).read_text()
    match = re.search("^function " + name + "\\([^\\n]*\\n.*?^}", text, re.M | re.S)
    if not match:
        raise ValueError(f"Missing protocol function: {name}")
    return match.group()


def rename(text: str) -> str:
    renamed = checked_replace(text, "skyyrose_see_", "skyyrose2_analytics_")
    # Not every projection contains translated strings (relay fixture has none).
    return renamed.replace("'skyyrose'", "'skyyrose-flagship-2'")


def output(file: str, text: str) -> None:
    PENDING[file] = text


def checked_replace(text: str, old: str, new: str) -> str:
    if old not in text:
        raise ValueError(f"Missing projection anchor: {old!r}")
    return text.replace(old, new)


def canonical_php(text: str) -> str:
    program = "$out = []; foreach (token_get_all(stream_get_contents(STDIN), TOKEN_PARSE) as $t) {\nif (is_array($t)) { if (in_array($t[0], [T_WHITESPACE,T_COMMENT,T_DOC_COMMENT], true)) continue; $out[] = [$t[0],$t[1]]; } else { $out[] = $t; }\n} $stable = []; foreach ($out as $i => $t) {\nif ($t === ',' && in_array($out[$i + 1] ?? null, [')', ']'], true)) continue;\n$stable[] = $t;\n} echo json_encode($stable, JSON_THROW_ON_ERROR);"
    return subprocess.run(
        ["php", "-r", program], input=text, text=True, capture_output=True, check=True
    ).stdout


def formatted(file: str, text: str) -> str:
    if Path(file).suffix not in {".js", ".cjs", ".css"}:
        return text
    prettier = THEME.parents[1] / "node_modules/prettier/bin/prettier.cjs"
    return subprocess.run(
        ["node", str(prettier), "--stdin-filepath", str(THEME / file)],
        input=text,
        text=True,
        capture_output=True,
        check=True,
    ).stdout


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Read-only parity validation")
    args = parser.parse_args()
    PENDING.clear()
    functions = []
    for name in [
        "allowed_backend_hosts",
        "is_safe_url",
        "parse_api_response",
        "analytics_binding",
        "relay_analytics",
    ]:
        functions.append(function("inc/fastapi-client.php", "skyyrose_see_" + name))
    for name in ["analytics_key", "rest_events_permission", "sanitize_events"]:
        functions.append(function("inc/rest-api-experience.php", "skyyrose_see_" + name))
    receiver = function("inc/rest-api-experience.php", "skyyrose_see_rest_receive_events")
    receiver = (
        receiver[: receiver.index("\t// Existing WP counters")]
        + "\treturn new WP_REST_Response( $ack, 200 );\n}"
    )
    functions.append(receiver)
    output(
        "inc/analytics-protocol.php",
        "<?php\n/**\n * Generated by scripts/sync-analytics.py; edit the V1 protocol, then regenerate.\n *\n * @package SkyyRoseFlagship2\n */\n\ndefined( 'ABSPATH' ) || exit;\n\n"
        + rename("\n\n".join(functions))
        + "\n",
    )
    banner = checked_replace(
        (SOURCE / "template-parts/cookie-consent.php").read_text(),
        "'skyyrose'",
        "'skyyrose-flagship-2'",
    )
    banner = checked_replace(banner, "analytics and personalization", "analytics")
    output("template-parts/cookie-consent.php", banner)
    output(
        "assets/css/cookie-consent.css",
        checked_replace(
            (SOURCE / "assets/css/cookie-consent.css").read_text(),
            "calc(var(--skyyrose-mobile-nav-h, 72px) + env(safe-area-inset-bottom))",
            "env(safe-area-inset-bottom)",
        ),
    )
    collector = (SOURCE / "assets/js/experience-analyzer.js").read_text()
    collector = checked_replace(
        checked_replace(
            checked_replace(
                checked_replace(collector, ".holo[data-sku]", ".sr2-c-editorial-card[data-sku]"),
                "'.holo__buy'",
                "'.sr2-c-editorial-card__actions .button, .sr2-c-editorial-card__media, .sr2-c-editorial-card__title a'",
            ),
            "'.holo__wishlist'",
            "'[data-analytics-wishlist]'",
        ),
        "'.holo__quickview'",
        "'[data-quick-view]'",
    )
    collector = checked_replace(
        collector,
        "request = fetch('/?rest_route=/skyyrose/v1/analytics/events&k=' + encodeURIComponent(key), {",
        "var configured = window.skyyroseSEE && window.skyyroseSEE.endpoint;\n      if (!configured) throw new Error('analytics_endpoint_missing');\n      var endpoint = new URL(configured, window.location.href);\n      if (endpoint.origin !== window.location.origin) throw new Error('analytics_endpoint_origin');\n      endpoint.searchParams.set('k', key);\n      request = fetch(endpoint.href, {",
    )
    output("assets/js/experience-analyzer.js", collector)
    tests = (SOURCE / "tests/analytics/consent.test.cjs").read_text()
    tests = tests[: tests.index("test('personalization is gated")]
    tests = checked_replace(
        checked_replace(
            checked_replace(tests, ".holo__buy", ".sr2-c-editorial-card__actions .button"),
            ".holo__wishlist",
            "[data-quick-view]",
        ),
        ".holo",
        ".sr2-c-editorial-card",
    )
    tests = checked_replace(
        checked_replace(
            checked_replace(
                checked_replace(
                    tests,
                    "assert.equal(card.tagName, 'DIV');",
                    "assert.equal(card.tagName, 'ARTICLE');",
                ),
                "assert.equal(buy.dataset.productId, '9');",
                "assert.equal(buy.dataset.nativeProduct, '9');",
            ),
            "assert.equal(wishlist.dataset.productId, '9');",
            "assert.equal(wishlist.dataset.quickViewName, 'Fixture product');",
        ),
        "['buy', 'wishlist']",
        "['buy', 'quickview']",
    )
    tests = checked_replace(
        tests,
        "w.skyyroseSEE = { key: 'public-token' };",
        "w.skyyroseSEE = { key: 'public-token', endpoint: '/store/wp-json/skyyrose/v1/analytics/events' };",
    )
    tests = checked_replace(
        tests,
        "const events = f.requests[0].body.events;",
        "assert.ok(f.requests[0].url.includes('/store/wp-json/skyyrose/v1/analytics/events'));\n    const events = f.requests[0].body.events;",
    )
    tests += """
for (const endpoint of ['', 'https://untrusted.test/ingest']) {
  test('V2 refuses missing or cross-origin endpoint: ' + endpoint, async () => {
    const f = fixture({ consent: 'accepted' });
    f.w.skyyroseSEE.endpoint = endpoint;
    f.tick();
    await settle();
    assert.equal(f.requests.length, 0);
    assert.ok(f.delivery.includes('unavailable'));
    f.close();
  });
}
"""
    output("tests/analytics/consent.test.cjs", tests)
    browser = checked_replace(
        (SOURCE / "tests/analytics/browser-consent.test.cjs").read_text(),
        ".holo__buy",
        ".sr2-c-editorial-card__actions .button",
    )
    browser = checked_replace(
        browser,
        "      await page.locator('.sr2-c-editorial-card__actions .button').click();",
        "      await page.evaluate(() => document.querySelector('.sr2-c-editorial-card__actions .button').addEventListener('click', event => event.preventDefault()));\n      await page.locator('.sr2-c-editorial-card__actions .button').click();",
    )
    browser = checked_replace(
        browser,
        "window.skyyroseSEE={key:'public-token'}",
        "window.skyyroseSEE={key:'public-token',endpoint:'/store/wp-json/skyyrose/v1/analytics/events'}",
    )
    browser = checked_replace(
        browser,
        "const body = route.request().postDataJSON();",
        "assert.ok(route.request().url().includes('/store/wp-json/skyyrose/v1/analytics/events'));\n        const body = route.request().postDataJSON();",
    )
    browser = checked_replace(browser, "/tmp/e2e-theme-consent-", "/tmp/e2e-v2-theme-consent-")
    output("tests/analytics/browser-consent.test.cjs", browser)
    relay = (SOURCE / "tests/analytics/relay.php").read_text()
    # V2 has no local engagement projection/table. Keep the shared relay tests,
    # excluding only V1 storage setup and its separately covered endpoint replay.
    storage_start = relay.index("define( 'SKYYROSE_SEE_DB_VERSION'")
    storage_end = relay.index("function wp_remote_post", storage_start)
    relay = relay[:storage_start] + relay[storage_end:]
    replay_start = relay.index("// A partially delivered remote batch")
    replay_end = relay.index("putenv( 'SKYYROSE_ANALYTICS_SECRET' );", replay_start)
    relay = relay[:replay_start] + relay[replay_end:]
    relay = checked_replace(
        relay, "if ( 'skyyrose_see_db_version' === $name ) { return SKYYROSE_SEE_DB_VERSION; } ", ""
    )

    relay = checked_replace(
        relay,
        "require dirname( __DIR__, 2 ) . '/inc/fastapi-client.php';",
        "require dirname( __DIR__, 2 ) . '/inc/analytics.php';\nputenv( 'SKYYROSE_ANALYTICS_API_URL=http://127.0.0.1:8089' );",
    )
    relay = checked_replace(
        checked_replace(
            relay, "require dirname( __DIR__, 2 ) . '/inc/rest-api-experience.php';\n", ""
        ),
        "require dirname( __DIR__, 2 ) . '/inc/personalization.php';\n",
        "",
    )
    relay = "\n".join(
        line
        for line in relay.split("\n")
        if not (
            line.startswith("check(")
            and ("get_visitor_hash" in line or "engagement_product_click" in line)
        )
    )
    output("tests/analytics/relay.php", rename(relay))
    prepared = {file: formatted(file, text) for file, text in PENDING.items()}
    for file, text in prepared.items():
        path = THEME / file
        if args.check:
            actual = path.read_text() if path.exists() else ""
            equal = (
                canonical_php(actual) == canonical_php(text)
                if path.suffix == ".php"
                else actual == text
            )
            if not equal:
                raise ValueError(f"Stale analytics projection: {file}")
    if not args.check:
        for file, text in prepared.items():
            path = THEME / file
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    print(
        "PASS: standalone V2 analytics projections "
        + ("match V1 contract." if args.check else "generated.")
    )


if __name__ == "__main__":
    main()
