<?php
/**
 * Generated by scripts/sync-analytics.py; edit the V1 protocol, then regenerate.
 *
 * @package SkyyRoseFlagship2
 */

defined( 'ABSPATH' ) || exit;

function skyyrose2_analytics_allowed_backend_hosts(): array {
	return apply_filters(
		'skyyrose2_analytics_allowed_backend_hosts',
		array(
			'api.devskyy.app',         // custom domain — REST backend + /mcp mount.
			'devskyy-backend.fly.dev', // REST backend Fly app.
			'devskyy-api.fly.dev',     // MCP Fly app.
			'localhost',               // local dev only (loopback still range-gated below).
			'127.0.0.1',
		)
	);
}

function skyyrose2_analytics_is_safe_url( string $url ): bool {
	$parsed = wp_parse_url( $url );
	if ( ! $parsed || empty( $parsed['host'] ) ) {
		return false;
	}

	$scheme = strtolower( $parsed['scheme'] ?? '' );
	if ( 'http' !== $scheme && 'https' !== $scheme ) {
		return false;
	}

	$host = strtolower( trim( $parsed['host'], '[]' ) );

	// Primary defense: the host must be known DevSkyy infrastructure. This runs
	// BEFORE any DNS resolution, so a rebindable attacker domain is refused
	// outright and the check-time/connect-time TOCTOU window is closed by
	// construction (the connection can only target an allowlisted host whose DNS
	// we control). The range filtering below is retained as defense-in-depth.
	if ( ! in_array( $host, skyyrose2_analytics_allowed_backend_hosts(), true ) ) {
		return false;
	}

	// Resolve to a target IP. Critically: if the host is ALREADY an IP literal
	// (v4 or v6), use it directly — gethostbyname() returns a literal unchanged,
	// and the previous `$ip !== $host` guard then SKIPPED the range check
	// entirely, letting http://10.0.0.1/, http://127.0.0.1/, http://[::1]/ etc.
	// pass. Now the private+reserved-range filter runs unconditionally.
	if ( filter_var( $host, FILTER_VALIDATE_IP ) ) {
		$ip = $host;
	} else {
		$ip = gethostbyname( $host ); // IPv4 resolution; returns $host on failure.
		if ( $ip === $host ) {
			// Unresolvable (or IPv6-only host gethostbyname can't handle) — fail
			// closed rather than allow an unvalidated destination.
			return false;
		}
	}

	// Allow loopback in local development only.
	if ( str_starts_with( $ip, '127.' ) && wp_get_environment_type() === 'local' ) {
		return true;
	}

	// Always apply private + reserved range filtering, for both IPv4 and IPv6.
	// NO_PRIV_RANGE covers RFC 1918; NO_RES_RANGE covers loopback, link-local
	// (169.254/16 — the cloud-metadata range), multicast, and IPv6 equivalents.
	if ( ! filter_var( $ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE ) ) {
		return false;
	}

	return true;
}

function skyyrose2_analytics_parse_api_response( $response ): ?array {
	if ( is_wp_error( $response ) ) {
		return null;
	}

	$code = wp_remote_retrieve_response_code( $response );
	if ( $code < 200 || $code >= 300 ) {
		return null;
	}

	$body = wp_remote_retrieve_body( $response );
	$data = json_decode( $body, true );

	return is_array( $data ) ? $data : null;
}

function skyyrose2_analytics_analytics_binding(): ?array {
	$binding = array();
	foreach ( array( 'site_id', 'environment', 'secret' ) as $key ) {
		$name            = 'SKYYROSE_ANALYTICS_' . strtoupper( $key );
		$binding[ $key ] = defined( $name ) ? constant( $name ) : getenv( $name );
	}
	if ( ! is_string( $binding['site_id'] ) || ! preg_match( '/^[A-Za-z0-9_-]{1,80}$/', $binding['site_id'] )
		|| ! in_array( $binding['environment'], array( 'staging', 'production', 'test' ), true )
		|| ! is_string( $binding['secret'] ) || strlen( $binding['secret'] ) < 32 ) {
		return null;
	}
	return $binding;
}

function skyyrose2_analytics_relay_analytics( array $events ): ?array {
	$binding = skyyrose2_analytics_analytics_binding();
	$url     = skyyrose2_analytics_get_fastapi_url() . '/api/v1/analytics/ingest';
	if ( null === $binding || ! $events || ! skyyrose2_analytics_is_safe_url( $url ) ) {
		return null;
	}
	// HMAC credentials must never traverse HTTP outside a local test fixture.
	if ( 'https' !== wp_parse_url( $url, PHP_URL_SCHEME ) && 'local' !== wp_get_environment_type() ) {
		return null;
	}
	$body = wp_json_encode(
		array(
			'schema_version' => 1,
			'site_id'        => $binding['site_id'],
			'environment'    => $binding['environment'],
			'consent'        => 'accepted',
			'sent_at'        => gmdate( 'Y-m-d\TH:i:s\Z' ),
			'events'         => $events,
		)
	);
	if ( ! is_string( $body ) ) {
		return null;
	}
	if ( strlen( $body ) > 65536 ) {
		// Split exact encoded bytes, including the server-owned envelope. Partial
		// delivery is retried with unchanged IDs and deduplicated by the backend.
		if ( count( $events ) < 2 ) {
			return null;
		}
		$halves = array_chunk( $events, (int) ceil( count( $events ) / 2 ) );
		$first  = skyyrose2_analytics_relay_analytics( $halves[0] );
		if ( null === $first ) {
			return null;
		}
		$second = skyyrose2_analytics_relay_analytics( $halves[1] );
		if ( null === $second ) {
			return null;
		}
		$first['accepted']   += $second['accepted'];
		$first['duplicates'] += $second['duplicates'];
		$first['event_ids']   = array_merge( $first['event_ids'], $second['event_ids'] );
		return $first;
	}
	$timestamp = (string) time();
	$response  = wp_remote_post(
		$url,
		array(
			'timeout'     => 10,
			'blocking'    => true,
			'redirection' => 0,
			'sslverify'   => true,
			'headers'     => array(
				'Content-Type'                   => 'application/json',
				'X-SkyyRose-Analytics-Timestamp' => $timestamp,
				'X-SkyyRose-Analytics-Signature' => hash_hmac( 'sha256', $timestamp . '.' . $body, $binding['secret'] ),
			),
			'body'        => $body,
		)
	);
	if ( is_wp_error( $response ) || 200 !== wp_remote_retrieve_response_code( $response ) ) {
		return null;
	}
	$ack = skyyrose2_analytics_parse_api_response( $response );
	$ids = array_column( $events, 'event_id' );
	if ( ! is_array( $ack ) || 'accepted' !== ( $ack['status'] ?? '' )
		|| ( $ack['site_id'] ?? '' ) !== $binding['site_id'] || ( $ack['environment'] ?? '' ) !== $binding['environment']
		|| ( $ack['event_ids'] ?? null ) !== $ids || ! is_int( $ack['accepted'] ?? null ) || ! is_int( $ack['duplicates'] ?? null )
		|| $ack['accepted'] < 0 || $ack['duplicates'] < 0 || count( $events ) !== $ack['accepted'] + $ack['duplicates'] ) {
		return null;
	}
	return $ack;
}

function skyyrose2_analytics_analytics_key(): string {
	$key = get_option( 'skyyrose2_analytics_analytics_key', '' );
	if ( ! is_string( $key ) || '' === $key ) {
		$key = wp_generate_password( 32, false, false );
		add_option( 'skyyrose2_analytics_analytics_key', $key, '', true );
	}
	return $key;
}

function skyyrose2_analytics_rest_events_permission( WP_REST_Request $request ) {
	if ( 'accepted' !== sanitize_text_field( wp_unslash( $_COOKIE['skyyrose_cookie_consent'] ?? '' ) ) || 'accepted' !== $request->get_param( 'consent' ) ) {
		return new WP_Error( 'analytics_consent_required', esc_html__( 'Analytics consent is required.', 'skyyrose-flagship-2' ), array( 'status' => 403 ) );
	}
	$provided = (string) $request->get_param( 'k' );
	if ( '' !== $provided && hash_equals( skyyrose2_analytics_analytics_key(), $provided ) ) {
		return true;
	}

	return new WP_Error(
		'rest_forbidden',
		esc_html__( 'Invalid analytics key.', 'skyyrose-flagship-2' ),
		array( 'status' => 401 )
	);
}

function skyyrose2_analytics_sanitize_events( array $events ): array {
	$types      = array( 'page_view', 'collection_view', 'product_view', 'product_click', 'add_to_cart', 'remove_from_cart', 'begin_checkout', 'lookbook_view', 'hotspot_click', 'search', 'size_guide_open', 'newsletter_signup', 'scroll_depth', 'next_world' );
	$pages      = array( 'home', 'collection', 'product', 'shop', 'cart', 'checkout', 'lookbook', 'immersive', 'search', 'other' );
	$keys       = array( 'event_id', 'session_id', 'event_type', 'occurred_at', 'page_type', 'collection', 'target', 'value', 'properties', 'synthetic' );
	$properties = array( 'action', 'depth', 'sku', 'product_id', 'quantity', 'position', 'scene', 'direction', 'source', 'variant', 'route', 'utm_source', 'utm_medium', 'utm_campaign', 'utm_content' );
	$ids        = array();
	foreach ( $events as $event ) {
		if ( ! is_array( $event ) || array_diff( array_keys( $event ), $keys ) ) {
			return array();
		}
		foreach ( array( 'event_id', 'session_id', 'event_type', 'occurred_at', 'page_type' ) as $required ) {
			if ( ! isset( $event[ $required ] ) || ! is_string( $event[ $required ] ) ) {
				return array();
			}
		}
		if ( ! preg_match( '/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/', $event['event_id'] )
			|| isset( $ids[ $event['event_id'] ] )
			|| ! preg_match( '/^[A-Za-z0-9_-]{16,100}$/', $event['session_id'] )
			|| ! in_array( $event['event_type'], $types, true )
			|| ! in_array( $event['page_type'], $pages, true )
			|| ! preg_match( '/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?Z$/', $event['occurred_at'] )
			|| false === strtotime( $event['occurred_at'] )
			|| gmdate( 'Y-m-d\TH:i:s', strtotime( $event['occurred_at'] ) ) !== substr( $event['occurred_at'], 0, 19 )
			|| strtotime( $event['occurred_at'] ) < time() - DAY_IN_SECONDS
			|| strtotime( $event['occurred_at'] ) > time() + 60 ) {
			return array();
		}
		$ids[ $event['event_id'] ] = true;
		foreach ( array( 'collection', 'target' ) as $key ) {
			if ( isset( $event[ $key ] ) && ( ! is_string( $event[ $key ] ) || ! preg_match( '/^[A-Za-z0-9_\/.-]{1,160}$/', $event[ $key ] ) || ( 'collection' === $key && strlen( $event[ $key ] ) > 100 ) ) ) {
				return array();
			}
		}
		if ( isset( $event['value'] ) && ( ( ! is_int( $event['value'] ) && ! is_float( $event['value'] ) ) || ! is_finite( (float) $event['value'] ) || $event['value'] < 0 || $event['value'] > 1000000 ) ) {
			return array();
		}
		if ( array_key_exists( 'synthetic', $event ) && ! is_bool( $event['synthetic'] ) ) {
			return array();
		}
		if ( array_key_exists( 'properties', $event ) ) {
			if ( ! is_array( $event['properties'] ) || array_diff( array_keys( $event['properties'] ), $properties ) ) {
				return array();
			}
			foreach ( $event['properties'] as $value ) {
				if ( is_string( $value ) ) {
					if ( ! preg_match( '/^[A-Za-z0-9_\/.-]{1,160}$/', $value ) ) {
						return array();
					}
				} elseif ( ( ! is_int( $value ) && ! is_float( $value ) ) || ! is_finite( (float) $value ) || $value < 0 || $value > 1000000 ) {
					return array();
				}
			}
		}
	}
	return array_values( $events );
}

function skyyrose2_analytics_rest_receive_events( WP_REST_Request $request ): WP_REST_Response {
	// Repeat consent at the mutation boundary, including direct internal calls.
	if ( 'accepted' !== sanitize_text_field( wp_unslash( $_COOKIE['skyyrose_cookie_consent'] ?? '' ) ) || 'accepted' !== $request->get_param( 'consent' ) ) {
		return new WP_REST_Response(
			array(
				'status' => 'rejected',
				'error'  => 'consent_required',
			),
			403
		);
	}
	$ip         = sanitize_text_field( wp_unslash( $_SERVER['REMOTE_ADDR'] ?? '0.0.0.0' ) );
	$rate_key   = 'skyyrose2_analytics_rate_' . md5( $ip );
	$rate_count = (int) get_transient( $rate_key );
	if ( $rate_count >= 10 ) {
		return new WP_REST_Response(
			array(
				'status' => 'unavailable',
				'error'  => 'rate_limited',
			),
			429
		);
	}
	set_transient( $rate_key, $rate_count + 1, MINUTE_IN_SECONDS );
	$raw = $request->get_param( 'events' );
	if ( 1 !== $request->get_param( 'schema_version' ) || ! is_array( $raw ) || count( $raw ) < 1 || count( $raw ) > 50 ) {
		return new WP_REST_Response(
			array(
				'status' => 'rejected',
				'error'  => 'invalid_events',
			),
			422
		);
	}
	$events = skyyrose2_analytics_sanitize_events( $raw );
	if ( count( $events ) !== count( $raw ) ) {
		return new WP_REST_Response(
			array(
				'status' => 'rejected',
				'error'  => 'invalid_events',
			),
			422
		);
	}
	$ack = function_exists( 'skyyrose2_analytics_relay_analytics' ) ? skyyrose2_analytics_relay_analytics( $events ) : null;
	if ( null === $ack ) {
		return new WP_REST_Response(
			array(
				'status' => 'unavailable',
				'error'  => 'analytics_unavailable',
			),
			503
		);
	}
	return new WP_REST_Response( $ack, 200 );
}
